config/routes.rb
Nkapp::Application.routes.draw do

  resources :comments
  
  resources :commissions do
    resources :protocols
  end

  resources :pictures, :only => [:index, :create]
  get "verify/index"

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show
  resources :home
  resources :verify

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commission
end

app/models/commission.rb
class Commission < ActiveRecord::Base
  has_ancestry
   
  belongs_to :election
  has_many :comments, :dependent => :destroy 
  has_many :protocols, :dependent => :destroy 
  has_many :votings, :dependent => :destroy 
  has_many :voting_dictionaries, :through => :votings
  def self.with_votes    
    self.includes(:votings,:voting_dictionaries)
  # .where("voting_dictionaries.main_role",true)
  end

  def get_names
    # self.election.voting_dictionaries.map(&:en_name)
  end

  def pct(target)
    10
    # self.votings.joins(:voting_dictionary).where(:voting_dictionary => {:en_name => target})
    # if self.send(target).to_i > 0
    #   if target == "poll"
    #     100 * self.valid_ballots.to_i/self.send(target).to_i
    #   else  
    #     100 * self.send(target).to_i/self.valid_ballots.to_i
    #   end
    # else
    #   0
    # end
  end
  
end

app/models/election.rb
class Election < ActiveRecord::Base  
  has_many :commissions, :dependent => :destroy
  has_many :voting_dictionaries, :dependent => :destroy 
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :protocol
  mount_uploader :picture, PictureUploader
  
  def to_jq_upload
  {
    "name" => read_attribute(:avatar),
    "size" => avatar.size,
    "url" => avatar.url,
    "thumbnail_url" => avatar.thumb.url,
    "delete_url" => picture_path(:id => id),
    "delete_type" => "DELETE" 
   }
  end
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  belongs_to :commission
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/models/voting.rb
class Voting < ActiveRecord::Base
  belongs_to :commission
  belongs_to :voting_dictionary

  validates_uniqueness_of :commission_id, :scope => :voting_dictionary_id

end

app/models/voting_dictionary.rb
class VotingDictionary < ActiveRecord::Base
  belongs_to :election
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @elections = Election.find(:all)
    # @commissions = Commission.roots
  end
  def show
    
    @commission = Commission.find(params[:id])
    @election = @commission.election
    # @commission = Commission.all(:include => :votings, :conditions => {:is_uik => false})
  end
end

app/controllers/uik_controller.rb
class UikController < ApplicationController
  def index
    @uiks = Commission.find :all, :joins => :comments
    # Commission.includes([:comments]).where(:is_uik=>true)
  end

  def show
    @uik = Commission.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end

end

app/controllers/verify_controller.rb
# encoding: utf-8
class VerifyController < ApplicationController
  def index
    @result = Array.new
    # commission = Commission.roots.first
    # Commission.roots.each do |commission|
      # commission.children.each {|child| tree_travel(commission)}
    # end
    # @result.uniq!

    # new stuff
    
  
      Commission.where(:uik_holder=>true).each do |uik_holder|        
        result = 0
        
        uik_holder.children.each do |uik_child|
          if uik_child.votings.exists?
            result = uik_child.votings.where(:voting_dictionary_id => 1).first.votes + result
          end
          # p uik_child.votings
        end
        
        if uik_holder.votings.exists? and uik_holder.votings.where(:voting_dictionary_id => 1).first.votes != result
          # print "#{uik_holder.name} | #{uik_holder.votings.first.votes} | #{result}\n" 
          uik_holder[:num_calc] = result
          @result << uik_holder
        end
      end
    
  end
  
  def tree_travel(commission)
    sum_result = Hash.new
    commission.children.each do |child|
      if child.has_children?
        tree_travel(child)
      else
        if child.is_uik
          #складываем данные по уикам
          sum_result[:poll] = sum_result[:poll].to_i + child[:poll].to_i
          sum_result[:name] = child.name
        end
      end
    end
    
    if sum_result[:poll] != commission[:poll] && !sum_result.empty?
      @result << {:name => commission[:name], :poll => commission[:poll], :summed_poll => sum_result[:poll]}
    end
    
  end
  def index_old
    @result = Array.new
    @trash = Array.new
    @commission = Commission.roots.first
    @commission.children.each do |child|
      @tmp = Hash.new
      @tmp[:name] = child.name
      @tmp[:poll_from_cik] = child.poll
      if child.has_children?
        child.children.each do |uik|

          @tmp[:poll] = uik.poll.to_i + @tmp[:poll].to_i
          @trash << uik[:name].gsub(/[УИК №]/,'')
        end
      end


      @result << @tmp
      
    end
          p @trash
          245.times do |i|
            p i if !@trash.include?(i.to_s)
            
          end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def suckerfish(node)
    fuc = lambda do |nodes|
      return "" if nodes.empty?
      return "<ul>" +
        nodes.inject("") do |string, (node, children)|
          string + "<li rel='#{node.id}'>" +
          node.name+
          fuc.call(children) +
          "</li>"
        end +
        "</ul>"
    end
    fuc.call(node.descendants.arrange)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commissions_helper.rb
module CommissionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  #data Атрибуты для УИК-а
  def filter_params(voting_table)
    {"data-attendance"=>voting_table.pct("poll"),
      "data-sr"=>voting_table.pct("sr"),
      "data-ldpr"=>voting_table.pct("ldpr"),
      "data-pr"=>voting_table.pct("pr"),
      "data-kprf"=>voting_table.pct("kprf"),
      "data-yabloko"=>voting_table.pct("yabloko"),
      "data-er"=>voting_table.pct("er"),
      "data-pd"=>voting_table.pct("pd")}
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
  def f_int(attrib,name)
    haml_tag :div, :class => "clearfix" do
      haml_tag :label, :for => "for"
      haml_tag :div, :class => "input" do
        haml_tag :input, :type => "input"
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verify_helper.rb
module VerifyHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Nkapp
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body{:class => params[:controller]}
    #container.container
      %header
        %nav
          %ul.hmenu
            = render 'shared/navigation'
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_\#{name}" if msg.is_a?(String)
      #main{:role => "main"}
        = yield
      %footer

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li
    = link_to('Logout', destroy_user_session_path, :method=>'delete')
- else
  %li
    = link_to('Login', new_user_session_path)
- if user_signed_in?
  %li
    = link_to('Edit account', edit_user_registration_path)
- else
  %li
    = link_to('Sign up', new_user_registration_path)

app/views/shared/_tree_item.haml
- if node.is_uik == false
  %div.tree-node-holder{id: node.id}  
    %div.node-name
      %div.name
        %h3{"id"=>node.id,"data-depth"=>node.depth}
          = node.name
          %a.ico-link.sprite-link{:href=>node.url}
          
            
      %div.root-voting-table
        %ul
          %li
            Явка:
            %b= "#{node.pct("poll")}%"            
          %li
            Спр. Россия:
            %b= "#{node.pct("sr")}%"
          %li
            ЛДПР:
            %b= "#{node.pct("ldpr")}%"
          %li  
            Патр. России:
            %b= "#{node.pct("pr")}%"
          %li  
            КПРФ:
            %b= "#{node.pct("kprf")}%"
          %li  
            Яблоко:
            %b= "#{node.pct("yabloko")}%"
          %li  
            Ед. Россия:
            %b= "#{node.pct("er")}%"
          %li  
            Правое дело
            %b= "#{node.pct("pd")}%"

    %div.filter
      Фильтровать по:
      %a{"data-placement"=>"right", "rel"=>"popover", "title"=>"меньше", "class"=>"filter-popover"}
        явке
      %div.hidden
        %div.filter-item
          %ul
            -5.times do |i|
              %li
                %a{"data-arg" => (i+1)*20,"data-receiver_id" => node.id, "data-filter" =>"attendance"}
                  ="#{(i+1)*20} %"
                  
    - node.children.each do |child|
      - if (child.is_uik == true) 
        %div.voting-table{filter_params(child)}
          %div.controllers
            %a.open-protocol-dialog.ico-doc_lines_stright.sprite-link{"data-id"=>child.id}
            %a.open-comment-dialog.ico-spechbubble_sq_line.sprite-link{"data-id"=>child.id}              
            = link_to "test", new_commission_protocol_path(child)
          %h5
            = link_to child.name, commission_path(child)
          .item_holder
            .item
              Явка
            .value{:class => "attendance-#{child.pct("poll")/10.to_i}"}
              = " #{child.pct("poll")} %"
          .item_holder
            .item
              Справ. Россия
            .value
              = child.sr         
          .item_holder
            .item
              ЛДПР
            .value    
              = child.ldpr         
          .item_holder
            .item
              Патриоты России
            .value    
              = child.pr
          .item_holder
            .item
              КПРФ
            .value              
              = child.kprf
          .item_holder
            .item
              Яблоко
            .value    
              = child.yabloko
          .item_holder
            .item
              Единая Россия
            .value    
              = child.er
          .item_holder
            .item
              Правое дело
            .value    
              = child.pd
      - else

        = render :partial => "shared/tree_item", :locals => {:node => child}

app/views/shared/_uploader.html.haml
%form#fileupload{:action => "//jquery-file-upload.appspot.com", :enctype => "multipart/form-data", :method => "POST"}
  .row
    .span16.fileupload-buttonbar
      .progressbar.fileupload-progressbar
        %div{:style => "width:0%;"}
      %span.btn.success.fileinput-button
        %span Ваши протоколы...
        %input{:multiple => "", :name => "files[]", :type => "file"}
      %button.btn.primary.start{:type => "submit"} Загрузить
      / %button.btn.info.cancel{:type => "reset"} Cancel upload
      / %button.btn.danger.delete{:type => "button"} Delete selected
      / %input.toggle{:type => "checkbox"}
  %br
    .row
      .span16
        %table.zebra-striped
          %tbody.files
          


:javascript
  var fileUploadErrors = {
      maxFileSize: 'File is too big',
      minFileSize: 'File is too small',
      acceptFileTypes: 'Filetype not allowed',
      maxNumberOfFiles: 'Max number of files exceeded',
      uploadedBytes: 'Uploaded bytes exceed file size',
      emptyResult: 'Empty file upload result'
  };
%script#template-upload{:type => "text/html"}
  {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
  %tr.template-upload.fade
    %td.preview
      %span.fade
    %td.name {%=file.name%}
    %td.size {%=o.formatFileSize(file.size)%}
    {% if (file.error) { %}
    %td.error{:colspan => "2"}
      %span.label.important Error
      {%=fileUploadErrors[file.error] || file.error%}
    {% } else if (o.files.valid && !i) { %}
    %td.progress
      .progressbar
        %div{:style => "width:0%;"}
    %td.start
      {% if (!o.options.autoUpload) { %}
      %button.btn.primary> Start
      {% } %}
    {% } else { %}
    %td{:colspan => "2"}
    {% } %}
    %td.cancel
      {% if (!i) { %}
      %button.btn.info> Cancel
      {% } %}
  {% } %}
%script#template-download{:type => "text/html"}
  {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
  %tr.template-download.fade
    {% if (file.error) { %}
    %td
    %td.name {%=file.name%}
    %td.size {%=o.formatFileSize(file.size)%}
    %td.error{:colspan => "2"}
      %span.label.important Error
      {%=fileUploadErrors[file.error] || file.error%}
    {% } else { %}
    %td.preview
      {% if (file.thumbnail_url) { %}
      %a{:href => "{%=file.url%}", :rel => "gallery", :title => "{%=file.name%}"}
        %img{:src => "{%=file.thumbnail_url%}"}/
      {% } %}
    %td.name
      %a{:href => "{%=file.url%}", :rel => "{%=file.thumbnail_url&&'gallery'%}", :title => "{%=file.name%}"} {%=file.name%}
    %td.size {%=o.formatFileSize(file.size)%}
    %td{:colspan => "2"}
    {% } %}
    %td.delete
      %button.btn.danger{"data-type" => "{%=file.delete_type%}", "data-url" => "{%=file.delete_url%}"} Delete
      %input{:name => "delete", :type => "checkbox", :value => "1"}
  {% } %}          